#!/bin/sh
sudo apt install python3.9 > nul
echo Updating...
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py > nul
echo Updating Dependencies...
python3.9 get-pip.py > nul
echo Starting...
python3.9 killer.py
